ESA/src/java/Bean/AddAirportBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bean;

import Command.CommandFactory;
import DTO.AirportDTO;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 *
 * @author Kayde
 */
@Named(value = "addAirportBean")
@RequestScoped
public class AddAirportBean {
    private String airportID;
    private String name;
    private String line1, line2, line3, line4, line5;
    private int noTerminals;
    private int noGates;

    public String getAirportID() {
        return airportID;
    }

    public String getName() {
        return name;
    }

    public String getLine1() {
        return line1;
    }

    public String getLine2() {
        return line2;
    }

    public String getLine3() {
        return line3;
    }

    public String getLine4() {
        return line4;
    }

    public String getLine5() {
        return line5;
    }

    public int getNoTerminals() {
        return noTerminals;
    }

    public int getNoGates() {
        return noGates;
    }

    public void setAirportID(String airportID) {
        this.airportID = airportID;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setLine1(String line1) {
        this.line1 = line1;
    }

    public void setLine2(String line2) {
        this.line2 = line2;
    }

    public void setLine3(String line3) {
        this.line3 = line3;
    }

    public void setLine4(String line4) {
        this.line4 = line4;
    }

    public void setLine5(String line5) {
        this.line5 = line5;
    }

    public void setNoTerminals(int noTerminals) {
        this.noTerminals = noTerminals;
    }

    public void setNoGates(int noGates) {
        this.noGates = noGates;
    }
    
    public String addAirport(){
        String[] address = new String[5];
        address[0] = line1;
        address[1] = line2;
        address[2] = line3;
        address[3] = line4;
        address[4] = line5;
        
        AirportDTO airport = new AirportDTO(airportID, name, noTerminals, noGates);
        airport.setLocation(address);
        if((Boolean)CommandFactory.createCommand(CommandFactory.ADD_AIRPORT, airport).execute()){
            return "/admin/airports.xhtml";
        }else{
            return "/admin/addairport.xhtml";
        }
    }
}

ESA/src/java/Bean/AddFlightBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bean;

import Command.CommandFactory;
import DTO.FlightDTO;
import DTO.RouteDTO;
import java.sql.Timestamp;
import java.util.Calendar;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 *
 * @author Kayde
 */
@Named(value = "addFlightBean")
@RequestScoped
public class AddFlightBean {
    //private int flightID;
    //private RouteDTO route;
    //private Calendar departureDateTime;
    //private String status;
    private int routeID;
    private Timestamp departureDateTime, arrivalDateTime;
    private String status;

    public void setRouteID(int routeID) {
        this.routeID = routeID;
    }

    public void setDepartureDateTime(Timestamp departureDateTime) {
        this.departureDateTime = departureDateTime;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public int getRouteID() {
        return routeID;
    }

    public Timestamp getDepartureDateTime() {
        return departureDateTime;
    }

    public String getStatus() {
        return status;
    }

    public Timestamp getArrivalDateTime() {
        return arrivalDateTime;
    }

    public void setArrivalDateTime(Timestamp arrivalDateTime) {
        this.arrivalDateTime = arrivalDateTime;
    }

    public String addFlight(){
        
        if(arrivalDateTime.before(departureDateTime)){
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Arrival is before Departure!"));
            return "";
        }
        
        FlightDTO flight = new FlightDTO(new RouteDTO(routeID), departureDateTime, arrivalDateTime, status);
        CommandFactory.createCommand(CommandFactory.ADD_FLIGHT, flight).execute();
        return "/index.xhtml";
    }
}

ESA/src/java/Bean/AddPlaneBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bean;

import Command.CommandFactory;
import DTO.PlaneDTO;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 *
 * @author Kayde
 */
@Named(value = "addPlaneBean")
@RequestScoped
public class AddPlaneBean {
    private int Capacity, noCrew;
    private String planeModel;


    public int getCapacity() {
        return Capacity;
    }

    public int getNoCrew() {
        return noCrew;
    }

    public String getPlaneModel() {
        return planeModel;
    }

    public void setCapacity(int Capacity) {
        this.Capacity = Capacity;
    }

    public void setNoCrew(int noCrew) {
        this.noCrew = noCrew;
    }

    public void setPlaneModel(String planeModel) {
        this.planeModel = planeModel;
    }
    
    public String addPlane(){
        PlaneDTO plane = new PlaneDTO(planeModel, Capacity, noCrew);
        CommandFactory.createCommand(CommandFactory.ADD_PLANE, plane).execute();
        return "index.xhtml";
    }
}

ESA/src/java/Bean/AddRouteBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bean;

import Command.CommandFactory;
import DTO.AirportDTO;
import DTO.PlaneDTO;
import DTO.RouteDTO;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 *
 * @author Kayde
 */
@Named(value = "addRouteBean")
@RequestScoped
public class AddRouteBean {
    //private int routeID;
    //private AirportDTO destination;
    //private AirportDTO departureAirport;
    //private PlaneDTO plane;
    
    private String airport1ID, airport2ID;
    private int planeID;

    public String getAirport1ID() {
        return airport1ID;
    }

    public String getAirport2ID() {
        return airport2ID;
    }

    public int getPlaneID() {
        return planeID;
    }

    public void setAirport1ID(String airport1ID) {
        this.airport1ID = airport1ID;
    }

    public void setAirport2ID(String airport2ID) {
        this.airport2ID = airport2ID;
    }

    public void setPlaneID(int planeID) {
        this.planeID = planeID;
    }
    
    public String addRoute(){
        
        if(airport1ID.equals(airport2ID)){
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Departure Airport and Destination Airport cannot be the same!")); 
        }else{
            RouteDTO route = new RouteDTO(new AirportDTO(airport1ID), new AirportDTO(airport2ID), new PlaneDTO(planeID));
            if((Boolean)CommandFactory.createCommand(CommandFactory.ADD_ROUTE, route).execute()){ 
                return "index.xhtml";
            }
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Route Already Exists!")); 
        }
        return "addroute.xhtml";
    }
}

ESA/src/java/Bean/AirportBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bean;

import Command.CommandFactory;
import DTO.AirportDTO;
import java.util.ArrayList;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 *
 * @author Kayde
 */
@Named(value = "airportBean")
@RequestScoped
public class AirportBean {
    public ArrayList<AirportDTO>getAllAirports(){
        return (ArrayList<AirportDTO>)CommandFactory.createCommand(CommandFactory.GET_ALL_AIRPORTS).execute();
    }
    
    public void deleteAirport(String id){
        CommandFactory.createCommand(CommandFactory.DELETE_AIRPORT, id).execute(); 
    }
    
    public String[] getGates(String id){ //Not used yet, might never be
        ArrayList<String> test = new ArrayList<>();
        int gates = ((AirportDTO)CommandFactory.createCommand(CommandFactory.DELETE_AIRPORT, id).execute()).getNoGates();
        int terminals = ((AirportDTO)CommandFactory.createCommand(CommandFactory.DELETE_AIRPORT, id).execute()).getNoTerminals();
        
        for(int i = 0; i < terminals; i++){
            for(int j = 0; j < gates; j++){
                test.add("T: " + i + " G: " + j);
            }
        }
        return test.toArray(new String[test.size()]);
    }
}

ESA/src/java/Bean/PlaneBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bean;

import Command.CommandFactory;
import DTO.FlightDTO;
import DTO.PlaneDTO;
import java.util.ArrayList;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 *
 * @author Kayde
 */
@Named(value = "planeBean")
@RequestScoped
public class PlaneBean {
    public ArrayList<PlaneDTO>getAllPlanes(){
        return (ArrayList<PlaneDTO>)CommandFactory.createCommand(CommandFactory.GET_ALL_PLANES).execute();
    }
    
    public void deletePlane(int id){
        CommandFactory.createCommand(CommandFactory.DELETE_PLANE, id).execute();
    }
}

ESA/src/java/Bean/RouteBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bean;

import Command.CommandFactory;
import DTO.FlightDTO;
import DTO.RouteDTO;
import java.io.Serializable;
import java.util.ArrayList;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 *
 * @author Kayde
 */
@Named(value = "routeBean")
@SessionScoped
public class RouteBean implements Serializable{
    public RouteDTO getRouteDetails(int id){
        return (RouteDTO)CommandFactory.createCommand(CommandFactory.GET_ROUTE, id).execute();
    }
        
    public ArrayList<RouteDTO>getAllRoutes(){
        return (ArrayList<RouteDTO>)CommandFactory.createCommand(CommandFactory.GET_ALL_ROUTES).execute();
    }
    
    public void deleteRoute(int id){
        CommandFactory.createCommand(CommandFactory.DELETE_ROUTE, id).execute();
    }
}

ESA/web/admin/addairport.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets">    
    
    <h:head>
        <title>User Registration</title>
    </h:head>
    <h:body>
         <ui:composition template = "/templates/common.xhtml">
            <ui:define name="content">
                <div align="center" style="background-image:url(resources/img/background.png);height: 750px;">
                    <h2>Add Airport</h2>
                    <div class="displayContainer">
                        <h:form id="addairportForm">
                            <h3>Airport Details </h3>
                            <h:panelGrid columns="2" styleClass="displayTable" >
                            <h:outputText value="Airport Code: "/>
                            <h:inputText required="true" value="#{addAirportBean.airportID}" id="airportID"/>
                            <h:outputText value="Airport Name: "/>
                            <h:inputText required="true" value="#{addAirportBean.name}"/>
                            <h:outputText value="Number of Terminals: "/>
                            <h:inputText required="true" value="#{addAirportBean.noTerminals}" converterMessage="Interger input only!" />
                            <h:outputText value="Number of Gates: "/>
                            <h:inputText required="true" value="#{addAirportBean.noGates}" converterMessage="Interger input only!" />
                            
                           
                            
                            <h:outputText value="Address Line 1: "/>
                            <h:inputText value="#{addAirportBean.line1}"/>
                            <h:outputText value="Address Line 2: "/>
                            <h:inputText value="#{addAirportBean.line2}"/>
                            <h:outputText value="City: "/>
                            <h:inputText value="#{addAirportBean.line3}"/>
                            <h:outputText value="County: "/>
                            <h:inputText value="#{addAirportBean.line4}"/>
                            <h:outputText value="Postcode: "/>
                            <h:inputText value="#{addAirportBean.line5}"/>
                            <h:messages style="color: red" />
                            </h:panelGrid>
                            <h:commandButton value="Submit" action="#{addAirportBean.addAirport()}" />
                    </h:form>
                    </div>
                </div>
            </ui:define>
         </ui:composition>
    </h:body>
</html>

ESA/web/admin/addflight.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <h:head>
        <title>New Route!</title>
    </h:head>
    <h:body>
         <ui:composition template = "/templates/common.xhtml">
            <ui:define name="content">
                <div align="center" style="background-image:url(resources/img/background.png);height: 750px;">
                    <h2>Create a Flight!</h2>
                    <h:form>
                        <h:panelGrid columns="2" styleClass="displayTable">
                            <p><b>Route:</b></p>
                            <h:selectOneMenu value="#{addFlightBean.routeID}" required="true" requiredMessage="Please enter an airport!">
                                <f:selectItems value="#{routeBean.allRoutes}" var="route" itemLabel="#{route.departureAirport.name} to #{route.destination.name}" itemValue="#{route.routeID}" />
                            </h:selectOneMenu>
                            <p><b>Departure Time:</b><br>(dd/MM/yyyy HH:mm)</br></p>
                            <h:inputText value="#{addFlightBean.departureDateTime}"
                                        required="true"
                                        requiredMessage="Please enter the Date!">
                                <f:converter converterId="DateConverter" />
                                <f:validator validatorId="dateValidator" />
                            </h:inputText>
                            <p><b>Arrival Time:</b><br>(dd/MM/yyyy HH:mm)</br></p>
                            <h:inputText value="#{addFlightBean.arrivalDateTime}"
                                        required="true"
                                        requiredMessage="Please enter the Date!">
                                <f:converter converterId="DateConverter" />
                                <f:validator validatorId="dateValidator" />
                            </h:inputText>
                            <h:messages style="color: red" />
                        </h:panelGrid>
                        <h:commandButton value="Submit" action="#{addFlightBean.addFlight()}" />
                    </h:form>
                </div>
            </ui:define>
         </ui:composition>
    </h:body>
</html>

ESA/web/admin/addplane.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets">    
    
    <h:head>
        <title>User Registration</title>
    </h:head>
    <h:body>
         <ui:composition template = "/templates/common.xhtml">
            <ui:define name="content">
                <div align="center" style="background-image:url(resources/img/background.png);height: 750px;">
                    <h2>Add Plane</h2>
                    <div class="displayContainer">
                        <h:form>
                            <h:panelGrid columns="2" styleClass="displayTable">
                            <h:outputText value="Type: "/>
                            <h:inputText value="#{addPlaneBean.planeModel}"/>
                            <h:outputText value="Capacity: "/>
                            <h:inputText value="#{addPlaneBean.capacity}" converterMessage="Interger input only!" />
                            <h:outputText value="Crew Number: "/>
                            <h:inputText value="#{addPlaneBean.noCrew}" converterMessage="Interger input only!" />
                            </h:panelGrid>
                            <br></br>
                            <h:commandButton value="Submit" action="#{addPlaneBean.addPlane()}" />
                    </h:form>
                    </div>
                </div>
            </ui:define>
         </ui:composition>
    </h:body>
</html>

ESA/web/admin/addroute.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <h:head>
        <title>New Route!</title>
    </h:head>
    <h:body>
         <ui:composition template = "/templates/common.xhtml">
            <ui:define name="content">
                <div align="center" style="background-image:url(resources/img/background.png);height: 750px;">
                    <h2>Add Route</h2>
                    <h:form>
                        <h:panelGrid columns="2" styleClass="displayTable">
                            <p><b>Departing From:</b></p>
                            <h:selectOneMenu value="#{addRouteBean.airport1ID}" required="true" requiredMessage="Please enter an airport!">
                                <f:selectItems value="#{airportBean.allAirports}" var="airport" itemLabel="#{airport.name}" itemValue="#{airport.airportID}" />
                            </h:selectOneMenu>
                            <p><b>Destination:</b></p>
                            <h:selectOneMenu value="#{addRouteBean.airport2ID}" required="true" requiredMessage="Please enter an airport!">
                                <f:selectItems value="#{airportBean.allAirports}" var="airport2" itemLabel="#{airport2.name}" itemValue="#{airport2.airportID}" />
                            </h:selectOneMenu>
                            <p><b>Plane:</b></p>
                            <h:selectOneMenu value="#{addRouteBean.planeID}" required="true" requiredMessage="Please enter an airport!">
                                    <f:selectItems value="#{planeBean.allPlanes}" var="plane" itemLabel="#{plane.planeModel}" itemValue="#{plane.planeID}" />
                            </h:selectOneMenu>
                        </h:panelGrid>
                        <br></br>
                        <h:commandButton value="Submit" action="#{addRouteBean.addRoute()}" />
                    </h:form>
                </div>
            </ui:define>
         </ui:composition>
    </h:body>
</html>

ESA/web/admin/airports.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui = "http://java.sun.com/jsf/facelets">    
    
    <h:head>
        <title>Airports</title>
    </h:head>
    <h:body>
         <ui:composition template = "/templates/common.xhtml">
            <ui:define name="content">   
                <div align="center" class="displayContainer">
                <h:form >
                    <h:dataTable value="#{airportBean.allAirports}" 
                                 var="airport"
                                 cellpadding="10"
                                 styleClass="displayTable" 
                                 >
                        <h:column>
                            <f:facet name="header">Code</f:facet>
                            <h:outputText value="#{airport.airportID}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Name</f:facet>
                            <h:outputText value="#{airport.name}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Terminals</f:facet>
                            <h:outputText value="#{airport.noTerminals}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Gates</f:facet>
                            <h:outputText value="#{airport.noGates}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Address</f:facet>
                            <h:outputText value="#{airport.location[1]} : " />
                            <h:outputText value="#{airport.location[2]} : " />
                            <h:outputText value="#{airport.location[3]} : " />
                            <h:outputText value="#{airport.location[4]} : " />
                            <h:outputText value="#{airport.location[5]}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Actions</f:facet>
                            <h:commandButton onclick="if (! confirm('Really Delete This?\n(It will delete routes/flights/bookings relying on it)') ) { return false;}; return true;" value="Delete" action="${airportBean.deleteAirport(airport.airportID)}"/>
                        </h:column>
                    </h:dataTable>
                    <h:commandButton value="Add Airport" action="/admin/addairport.xhtml" rendered="#{UserBean.currentUser.isAdmin}"/>
                </h:form>
                </div>
            </ui:define>
         </ui:composition>
    </h:body>
</html>

ESA/web/admin/planes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui = "http://java.sun.com/jsf/facelets">    
    
    <h:head>
        <title>Flights</title>
    </h:head>
    <h:body>
         <ui:composition template = "/templates/common.xhtml">
            <ui:define name="content">
                <div align="center" class="displayContainer">
                <h:form >
                    <h:dataTable value="#{planeBean.allPlanes}" 
                                 var="plane"
                                 cellpadding="10"
                                 styleClass="displayTable" 
                                 headerClass="TableHeader"
                                 rowClasses="TableOddRow,TableEvenRow">
                        <h:column>
                            <f:facet name="header">Plane ID</f:facet>
                            <h:outputText value="#{plane.planeID}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Type</f:facet>
                            <h:outputText value="#{plane.planeModel}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Capacity</f:facet>
                            <h:outputText value="#{plane.capacity}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Crew Number</f:facet>
                            <h:outputText value="#{plane.noCrew}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Actions</f:facet>
                            <h:commandButton value="Delete" onclick="if (! confirm('Really Delete This?\n(It will delete routes/flights/bookings relying on it)') ) { return false;}; return true;" action="#{planeBean.deletePlane(plane.planeID)}" />
                        </h:column>
                    </h:dataTable>
                    <br></br>
                    <h:commandButton value="Add" action="/admin/addplane.xhtml" styleClass="myButtons" rendered="#{UserBean.currentUser.isAdmin}"/>
                </h:form>
                </div>
            </ui:define>
         </ui:composition>
    </h:body>
</html>

ESA/web/admin/routes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui = "http://java.sun.com/jsf/facelets">    
    
    <h:head>
        <title>Flights</title>
    </h:head>
    <h:body>
         <ui:composition template = "/templates/common.xhtml">
            <ui:define name="content"> 
                <div align="center" class="displayContainer">
                <h:form >
                    <h:dataTable value="#{routeBean.allRoutes}" 
                                 var="route"
                                 cellpadding="10"
                                 styleClass="displayTable" 
                                 >
                        <h:column>
                            <f:facet name="header">Route ID</f:facet>
                            <h:outputText value="#{route.routeID}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Departing</f:facet>
                            <h:outputText value="#{route.departureAirport.name}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Destination</f:facet>
                            <h:outputText value="#{route.destination.name}" />
                        </h:column>
                        
                        <h:column>
                            <f:facet name="header">Plane ID</f:facet>
                            <h:outputText value="#{route.plane.planeID}" />
                        </h:column>
                        <h:column>
                            <f:facet name="header">Plane Type</f:facet>
                            <h:outputText value="#{route.plane.planeModel}" />
                        </h:column>

                        <h:column>
                            <f:facet name="header">Actions</f:facet>
                            <h:commandButton onclick="if (! confirm('Really Delete This?\n(It will delete flights/bookings relying on it)') ) { return false;}; return true;" value="Delete" action="#{routeBean.deleteRoute(route.routeID)}" rendered="#{UserBean.currentUser.isAdmin}"/>
                        </h:column>
                    </h:dataTable>
                    <h:commandButton value="Add" action="/admin/addroute.xhtml" rendered="#{UserBean.currentUser.isAdmin}"/>
                </h:form>
                </div>
            </ui:define>
         </ui:composition>
    </h:body>
</html>